### ISSUE TITLE
Insufficient bounds in csound-expression-dynamic

### ISSUE THREAD

**Issue by sjakobi** [spell-music/csound-expression#72]
See https://matrix.haskell.org/#/package/csound-expression-dynamic.

I think at least you should require `base >= 4.10` in order to prevent failing builds with GHC < 8.2.

Ideally, the build plans of older releases would also be fixed by creating appropriate revisions. E.g. it looks like many versions should have a bound `hashable < 1.3.4` to prevent this error:

```
src/Csound/Dynamic/Types/Exp.hs:396:10: error:
    Duplicate instance declarations:
      instance Hashable1 IM.IntMap
        -- Defined at src/Csound/Dynamic/Types/Exp.hs:396:10
      instance Hashable1 IM.IntMap
        -- Defined in ‘hashable-1.3.4.1:Data.Hashable.Class’
    |
396 | instance Hashable1 IM.IntMap
    |          ^^^^^^^^^^^^^^^^^^^
```

For efficiently creating revisions in batches, I recommend https://github.com/hackage-trustees/hackage-cli. Its documentation is a bit [lacking](https://github.com/hackage-trustees/hackage-cli/issues/31) at the moment though.

https://github.com/phadej/trustee is a nice tool for doing matrix builds.

**Comment by anton-k** [comment]
Thanks for suggestion!
