### ISSUE TITLE
Fails to build with ghc-9.0.2 and ghc-9.2.4

### ISSUE THREAD

**Issue by michaelmariaott** [spell-music/csound-expression#76]
Hello,

I followed the Introduction, but `cabal install csound-expression` failed due to a build error. This is the build-log:

```
Warning: csound-expression-dynamic.cabal:3:23: Packages with 'cabal-version:
1.12' or later should specify a specific version of the Cabal spec of the form
'cabal-version: x.y'. Use 'cabal-version: 1.22'.
Configuring library for csound-expression-dynamic-0.3.9..
Preprocessing library for csound-expression-dynamic-0.3.9..
Building library for csound-expression-dynamic-0.3.9..
[ 1 of 15] Compiling Csound.Dynamic.Tfm.DeduceTypes ( src/Csound/Dynamic/Tfm/DeduceTypes.hs, dist/build/Csound/Dynamic/Tfm/DeduceTypes.o, dist/build/Csound/Dynamic/Tfm/DeduceTypes.dyn_o )
[ 2 of 15] Compiling Csound.Dynamic.Tfm.UnfoldMultiOuts ( src/Csound/Dynamic/Tfm/UnfoldMultiOuts.hs, dist/build/Csound/Dynamic/Tfm/UnfoldMultiOuts.o, dist/build/Csound/Dynamic/Tfm/UnfoldMultiOuts.dyn_o )
[ 3 of 15] Compiling Csound.Dynamic.Types.Exp ( src/Csound/Dynamic/Types/Exp.hs, dist/build/Csound/Dynamic/Types/Exp.o, dist/build/Csound/Dynamic/Types/Exp.dyn_o )

src/Csound/Dynamic/Types/Exp.hs:397:10: error:
    • Could not deduce (Data.Functor.Classes.Eq1 (PreInline a))
        arising from the superclasses of an instance declaration
      from the context: Hashable a
        bound by the instance declaration
        at src/Csound/Dynamic/Types/Exp.hs:397:10-46
    • In the instance declaration for ‘Hashable1 (PreInline a)’
    |
397 | instance Hashable a => Hashable1 (PreInline a)
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Csound/Dynamic/Types/Exp.hs:398:10: error:
    • Could not deduce (Data.Functor.Classes.Eq1 (Inline a))
        arising from the superclasses of an instance declaration
      from the context: Hashable a
        bound by the instance declaration
        at src/Csound/Dynamic/Types/Exp.hs:398:10-43
    • In the instance declaration for ‘Hashable1 (Inline a)’
    |
398 | instance Hashable a => Hashable1 (Inline a)
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Csound/Dynamic/Types/Exp.hs:399:10: error:
    • No instance for (Data.Functor.Classes.Eq1 RatedExp)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Hashable1 RatedExp’
    |
399 | instance Hashable1 RatedExp
    |          ^^^^^^^^^^^^^^^^^^

src/Csound/Dynamic/Types/Exp.hs:400:10: error:
    • No instance for (Data.Functor.Classes.Eq1 MainExp)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Hashable1 MainExp’
    |
400 | instance Hashable1 MainExp
    |          ^^^^^^^^^^^^^^^^^

src/Csound/Dynamic/Types/Exp.hs:401:10: error:
    • No instance for (Data.Functor.Classes.Eq1 PrimOr)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Hashable1 PrimOr’
    |
401 | instance Hashable1 PrimOr
    |          ^^^^^^^^^^^^^^^^
cabal: Failed to build csound-expression-dynamic-0.3.9 (which is required by
csound-expression-5.4.3). See the build log above for details.
```

**Comment by anton-k** [comment]
I guess this issue is related: https://github.com/spell-music/csound-expression/issues/72

So the problim is caused by the hashable package

**Comment by anton-k** [comment]
I've updated the package on github repo. Fixed lots of bugs an updated it to the new GHC.
I plan to remove hashable dependency.

But Ihavn't uploaded the new version to hackage yet.
So  it can be installed that way for a while

**Comment by georgefst** [comment]
I guess you still haven't fixed that one issue?

Love this package, and would be great to see an up-to-date working version on Hackage again!

**Comment by anton-k** [comment]
ok, i'll give it a try

**Comment by anton-k** [comment]
Please use newer versions of the ghc. Fixed today to work for ghc 9.6.4 and 9.8
